services:
  backend:
      build: ./backend
      depends_on:
        db:
          condition: service_healthy
      environment:
        - DATABASE_URL=${POSTGRES_URL}
      volumes:
        - ./backend:/app
      env_file:
        - .env.local
      command: python app.py

  db:
    image: postgres:14
    env_file:   # This will load the variables from the .env file
      - .env.local
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"  # Use port from .env
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
