name: Prod Deploy Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm test

      # - name: Install Playwright
      #  run: pnpm exec playwright install --with-deps

      # - name: Run E2E Tests
      #  run: pnpm exec playwright test

      - name: Build Project
        run: pnpm build

  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npx playwright install
      - name: Run Playwright tests
        run: npx playwright tests
        env: 
          HOME: /root
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install
      - name: Deploy to Vercel
        run: |
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
