name: Prod Deploy Pipeline

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.0
        with:
          version: 9.9.0
      - name: Install dependencies
        run: pnpm install

      # - name: Run Unit Tests
      #   run: pnpm test:unit

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: Build Project
        run: NEXT_PUBLIC_SKIP_SCRAPING=true pnpm build

      - name: Start the server and run E2E Tests
        run: |
          pnpm start &  # Start the production server in the background
          npx wait-on http://localhost:3000  # Wait until the server is ready
          pnpm test:e2e     # Run Playwright E2E tests
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v3
        with:
          version: 9.9.0
      - name: Install dependencies
        run: pnpm install
      - name: Deploy to Vercel
        run: |
          npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
